[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  
[build.environment]
  REACT_APP_BACKEND_URL = "https://your-backend-api.netlify.app"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200