#!/usr/bin/env python3
"""
Script pour compléter les 54 pays africains dans country_data.py
"""

# Ajouter les 16 pays manquants restants
REMAINING_COUNTRIES = {
    "COM": {'name': 'Comores', 'gdp_usd_2024': 1.4, 'gdp_per_capita_2024': 1554, 'population_2024': 900000, 'development_index': 0.558, 'hdi_africa_rank': 32, 'hdi_world_rank': 156, 'africa_rank': 54, 'growth_forecast_2024': '3.8%', 'external_debt_to_gdp_ratio': 32.1, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 8.9, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 5.1, 'foreign_reserves_months': 7.8, 'energy_cost_usd_kwh': 0.387, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -0.4, 'ease_of_doing_business_rank': 164, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'D'}, 'export_products': [{'name': 'Vanille', 'share': 38.2, 'value_usd': 0.08, 'type': 'Agriculture'}, {'name': 'Clous de girofle', 'share': 28.4, 'value_usd': 0.06, 'type': 'Agriculture'}, {'name': 'Ylang-ylang', 'share': 18.1, 'value_usd': 0.04, 'type': 'Agriculture'}], 'competitive_export_products': [{'name': 'Vanille premium', 'advantage': '2ème producteur mondial + qualité', 'potential_usd': 0.2, 'type': 'Agriculture'}, {'name': 'Tourisme de luxe', 'advantage': 'Îles paradisiaques + culture unique', 'potential_usd': 0.3, 'type': 'Services'}], 'infrastructure': {'routes_km': 880, 'routes_pavees_pct': 76.5, 'voies_ferrees_km': 0, 'ports_principaux': 1, 'ports_details': ['Moroni', 'Mutsamudu'], 'aeroports_internationaux': 1, 'aeroports_details': ['Moroni Prince Said Ibrahim']}, 'key_sectors': [{'name': 'Agriculture', 'pib_share': 35.0, 'description': 'Épices et huiles'}, {'name': 'Services', 'pib_share': 56.0, 'description': 'Commerce et tourisme'}], 'top_trade_partners': ['France', 'Inde', 'Allemagne', 'Pakistan', 'Turquie'], 'investment_opportunities': ['Agriculture de spécialité', 'Tourisme', 'Pêche'], 'main_exports': ['Vanille (38%)', 'Clous de girofle (28%)', 'Ylang-ylang (18%)'], 'main_imports': ['Produits alimentaires (25%)', 'Carburants (20%)', 'Machines (18%)'], 'zlecaf_potential': {'level': 'Modéré', 'description': 'Spécialisation produits de luxe', 'key_opportunities': ['Agriculture haute valeur', 'Tourisme haut de gamme']}},

    "CPV": {'name': 'Cap-Vert', 'gdp_usd_2024': 2.2, 'gdp_per_capita_2024': 3869, 'population_2024': 570000, 'development_index': 0.665, 'hdi_africa_rank': 9, 'hdi_world_rank': 128, 'africa_rank': 50, 'growth_forecast_2024': '4.8%', 'external_debt_to_gdp_ratio': 98.1, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 22.8, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 4.4, 'foreign_reserves_months': 5.2, 'energy_cost_usd_kwh': 0.298, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -0.8, 'ease_of_doing_business_rank': 137, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'C'}, 'export_products': [{'name': 'Poisson transformé', 'share': 87.2, 'value_usd': 0.2, 'type': 'Agriculture'}, {'name': 'Vêtements', 'share': 6.1, 'value_usd': 0.01, 'type': 'Manufacture'}], 'competitive_export_products': [{'name': 'Tourisme insulaire', 'advantage': 'Îles + climat + sécurité', 'potential_usd': 1.8, 'type': 'Services'}, {'name': 'Pêche industrielle', 'advantage': 'ZEE + position géographique', 'potential_usd': 0.8, 'type': 'Agriculture'}], 'infrastructure': {'routes_km': 1350, 'routes_pavees_pct': 78.0, 'voies_ferrees_km': 0, 'ports_principaux': 2, 'ports_details': ['Mindelo', 'Praia'], 'aeroports_internationaux': 4, 'aeroports_details': ['Praia Nelson Mandela', 'Mindelo Cesária Évora']}, 'key_sectors': [{'name': 'Services', 'pib_share': 73.0, 'description': 'Tourisme et services'}, {'name': 'Agriculture', 'pib_share': 8.0, 'description': 'Pêche'}], 'top_trade_partners': ['Espagne', 'Portugal', 'Pays-Bas', 'France', 'Chine'], 'investment_opportunities': ['Tourisme', 'Énergies renouvelables', 'Hub logistique'], 'main_exports': ['Poisson transformé (87%)', 'Vêtements (6%)'], 'main_imports': ['Produits alimentaires (23%)', 'Carburants (18%)'], 'zlecaf_potential': {'level': 'Modéré', 'description': 'Économie de services avec potentiel hub', 'key_opportunities': ['Hub logistique Atlantique', 'Tourisme régional']}},

    "DJI": {'name': 'Djibouti', 'gdp_usd_2024': 3.9, 'gdp_per_capita_2024': 3814, 'population_2024': 1000000, 'development_index': 0.524, 'hdi_africa_rank': 36, 'hdi_world_rank': 171, 'africa_rank': 48, 'growth_forecast_2024': '6.0%', 'external_debt_to_gdp_ratio': 78.1, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 4.2, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 2.8, 'foreign_reserves_months': 3.8, 'energy_cost_usd_kwh': 0.278, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -1.8, 'ease_of_doing_business_rank': 99, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'C'}, 'export_products': [{'name': 'Services portuaires', 'share': 80.0, 'value_usd': 2.8, 'type': 'Services'}, {'name': 'Sel', 'share': 15.0, 'value_usd': 0.02, 'type': 'Minier'}], 'competitive_export_products': [{'name': 'Services logistiques', 'advantage': 'Hub Corne Afrique + position géostratégique', 'potential_usd': 2.8, 'type': 'Services'}, {'name': 'Géothermie', 'advantage': 'Potentiel énorme + export régional', 'potential_usd': 1.2, 'type': 'Énergie'}], 'infrastructure': {'routes_km': 2893, 'routes_pavees_pct': 12.6, 'voies_ferrees_km': 97, 'ports_principaux': 1, 'ports_details': ['Djibouti (port autonome)'], 'aeroports_internationaux': 1, 'aeroports_details': ['Djibouti Ambouli']}, 'key_sectors': [{'name': 'Services', 'pib_share': 79.0, 'description': 'Transport et logistique'}, {'name': 'Agriculture', 'pib_share': 4.0, 'description': 'Élevage et pêche'}], 'top_trade_partners': ['Chine', 'Arabie Saoudite', 'Éthiopie', 'Inde', 'France'], 'investment_opportunities': ['Logistique', 'Géothermie', 'Hub financier'], 'main_exports': ['Services de transit (80%)', 'Sel (15%)'], 'main_imports': ['Produits alimentaires (25%)', 'Carburants (20%)'], 'zlecaf_potential': {'level': 'Très Élevé', 'description': 'Hub logistique régional stratégique', 'key_opportunities': ['Corridor Éthiopie', 'Services portuaires']}},

    "ERI": {'name': 'Érythrée', 'gdp_usd_2024': 2.1, 'gdp_per_capita_2024': 587, 'population_2024': 3600000, 'development_index': 0.459, 'hdi_africa_rank': 46, 'hdi_world_rank': 180, 'africa_rank': 50, 'growth_forecast_2024': '3.8%', 'external_debt_to_gdp_ratio': 165.7, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 32.1, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 12.3, 'foreign_reserves_months': 1.8, 'energy_cost_usd_kwh': 0.187, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -0.4, 'ease_of_doing_business_rank': 189, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'E'}, 'export_products': [{'name': 'Or', 'share': 62.1, 'value_usd': 0.4, 'type': 'Minier'}, {'name': 'Zinc', 'share': 18.2, 'value_usd': 0.12, 'type': 'Minier'}], 'competitive_export_products': [{'name': 'Or de haute pureté', 'advantage': 'Mines modernes + qualité + réserves', 'potential_usd': 1.2, 'type': 'Minier'}, {'name': 'Potasse', 'advantage': 'Gisements Danakil + demande régionale', 'potential_usd': 0.8, 'type': 'Minier'}], 'infrastructure': {'routes_km': 4010, 'routes_pavees_pct': 21.8, 'voies_ferrees_km': 306, 'ports_principaux': 2, 'ports_details': ['Massawa', 'Assab'], 'aeroports_internationaux': 1, 'aeroports_details': ['Asmara']}, 'key_sectors': [{'name': 'Services', 'pib_share': 61.0, 'description': 'Commerce'}, {'name': 'Industrie', 'pib_share': 22.0, 'description': 'Mines'}], 'top_trade_partners': ['Chine', 'Arabie Saoudite', 'Inde', 'Égypte'], 'investment_opportunities': ['Mines', 'Ports', 'Tourisme'], 'main_exports': ['Or (62%)', 'Zinc (18%)'], 'main_imports': ['Machines (25%)', 'Produits alimentaires (22%)'], 'zlecaf_potential': {'level': 'Modéré', 'description': 'Potentiel minier avec ouverture progressive', 'key_opportunities': ['Mines modernes', 'Hub mer Rouge']}},

    "GAB": {'name': 'Gabon', 'gdp_usd_2024': 20.8, 'gdp_per_capita_2024': 8917, 'population_2024': 2300000, 'development_index': 0.706, 'hdi_africa_rank': 8, 'hdi_world_rank': 112, 'africa_rank': 40, 'growth_forecast_2024': '2.9%', 'external_debt_to_gdp_ratio': 58.9, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 9.8, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 2.8, 'foreign_reserves_months': 2.8, 'energy_cost_usd_kwh': 0.087, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': 3.2, 'ease_of_doing_business_rank': 169, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'C'}, 'export_products': [{'name': 'Pétrole brut', 'share': 78.4, 'value_usd': 6.2, 'type': 'Énergie'}, {'name': 'Manganèse', 'share': 8.9, 'value_usd': 0.7, 'type': 'Minier'}, {'name': 'Bois', 'share': 6.2, 'value_usd': 0.5, 'type': 'Agriculture'}], 'competitive_export_products': [{'name': 'Manganèse haute qualité', 'advantage': '2ème producteur mondial + qualité', 'potential_usd': 2.1, 'type': 'Minier'}, {'name': 'Écotourisme de luxe', 'advantage': 'Parcs nationaux + biodiversité', 'potential_usd': 0.8, 'type': 'Services'}], 'infrastructure': {'routes_km': 10000, 'routes_pavees_pct': 12.0, 'voies_ferrees_km': 814, 'ports_principaux': 2, 'ports_details': ['Port-Gentil', 'Libreville'], 'aeroports_internationaux': 3, 'aeroports_details': ['Libreville Léon M\'ba', 'Port-Gentil']}, 'key_sectors': [{'name': 'Pétrole', 'pib_share': 35.0, 'description': 'Extraction offshore'}, {'name': 'Services', 'pib_share': 48.0, 'description': 'Commerce'}], 'top_trade_partners': ['Chine', 'États-Unis', 'France', 'Singapour'], 'investment_opportunities': ['Diversification post-pétrole', 'Écotourisme'], 'main_exports': ['Pétrole brut (78%)', 'Manganèse (9%)'], 'main_imports': ['Machines (22%)', 'Produits alimentaires (20%)'], 'zlecaf_potential': {'level': 'Élevé', 'description': 'Économie diversifiée avec richesses naturelles', 'key_opportunities': ['Transformation locale', 'Hub forestier']}},

    "GNQ": {'name': 'Guinée Équatoriale', 'gdp_usd_2024': 12.3, 'gdp_per_capita_2024': 8456, 'population_2024': 1450000, 'development_index': 0.596, 'hdi_africa_rank': 25, 'hdi_world_rank': 145, 'africa_rank': 44, 'growth_forecast_2024': '-3.2%', 'external_debt_to_gdp_ratio': 26.8, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 1.8, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 1.2, 'foreign_reserves_months': 1.2, 'energy_cost_usd_kwh': 0.098, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': 2.8, 'ease_of_doing_business_rank': 178, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'D'}, 'export_products': [{'name': 'Pétrole brut', 'share': 87.2, 'value_usd': 7.8, 'type': 'Énergie'}, {'name': 'Gaz naturel liquéfié', 'share': 8.1, 'value_usd': 0.7, 'type': 'Énergie'}], 'competitive_export_products': [{'name': 'Gaz naturel liquéfié', 'advantage': 'Réserves importantes + usine', 'potential_usd': 2.1, 'type': 'Énergie'}, {'name': 'Méthanol', 'advantage': 'Usine moderne + demande', 'potential_usd': 0.8, 'type': 'Industrie'}], 'infrastructure': {'routes_km': 2880, 'routes_pavees_pct': 7.4, 'voies_ferrees_km': 0, 'ports_principaux': 2, 'ports_details': ['Malabo', 'Bata'], 'aeroports_internationaux': 2, 'aeroports_details': ['Malabo', 'Bata']}, 'key_sectors': [{'name': 'Pétrole et gaz', 'pib_share': 68.0, 'description': 'Extraction offshore'}, {'name': 'Services', 'pib_share': 25.0, 'description': 'Commerce'}], 'top_trade_partners': ['Chine', 'Inde', 'Corée du Sud', 'États-Unis'], 'investment_opportunities': ['Diversification post-pétrole', 'Transformation'], 'main_exports': ['Pétrole brut (87%)', 'Gaz naturel (8%)'], 'main_imports': ['Machines (30%)', 'Produits alimentaires (25%)'], 'zlecaf_potential': {'level': 'Modéré', 'description': 'Économie pétrolière cherchant diversification', 'key_opportunities': ['Pétrochimie', 'Transformation locale']}},

    "LBY": {'name': 'Libye', 'gdp_usd_2024': 45.8, 'gdp_per_capita_2024': 6716, 'population_2024': 6800000, 'development_index': 0.718, 'hdi_africa_rank': 7, 'hdi_world_rank': 104, 'africa_rank': 22, 'growth_forecast_2024': '12.9%', 'external_debt_to_gdp_ratio': 155.8, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 89.4, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 2.1, 'foreign_reserves_months': 24.8, 'energy_cost_usd_kwh': 0.021, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': 12.8, 'ease_of_doing_business_rank': 186, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'E'}, 'export_products': [{'name': 'Pétrole brut', 'share': 92.1, 'value_usd': 18.8, 'type': 'Énergie'}, {'name': 'Gaz naturel', 'share': 4.2, 'value_usd': 0.9, 'type': 'Énergie'}], 'competitive_export_products': [{'name': 'Pétrole léger qualité', 'advantage': 'Réserves + qualité API élevée', 'potential_usd': 28.5, 'type': 'Énergie'}, {'name': 'Énergie solaire', 'advantage': 'Potentiel désertique énorme', 'potential_usd': 8.5, 'type': 'Énergie'}], 'infrastructure': {'routes_km': 100024, 'routes_pavees_pct': 34.0, 'voies_ferrees_km': 0, 'ports_principaux': 5, 'ports_details': ['Tripoli', 'Benghazi', 'Misrata'], 'aeroports_internationaux': 3, 'aeroports_details': ['Tripoli', 'Benghazi Benina']}, 'key_sectors': [{'name': 'Pétrole et gaz', 'pib_share': 65.0, 'description': 'Extraction'}, {'name': 'Services', 'pib_share': 25.0, 'description': 'Commerce'}], 'top_trade_partners': ['Italie', 'Chine', 'Allemagne', 'Espagne'], 'investment_opportunities': ['Reconstruction', 'Énergies renouvelables'], 'main_exports': ['Pétrole brut (92%)', 'Gaz naturel (4%)'], 'main_imports': ['Machines (25%)', 'Produits alimentaires (23%)'], 'zlecaf_potential': {'level': 'Élevé', 'description': 'Potentiel énorme post-stabilisation', 'key_opportunities': ['Hub énergétique', 'Reconstruction']}},

    "LSO": {'name': 'Lesotho', 'gdp_usd_2024': 2.5, 'gdp_per_capita_2024': 1164, 'population_2024': 2100000, 'development_index': 0.514, 'hdi_africa_rank': 37, 'hdi_world_rank': 168, 'africa_rank': 53, 'growth_forecast_2024': '2.2%', 'external_debt_to_gdp_ratio': 41.8, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 3.2, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 6.9, 'foreign_reserves_months': 4.1, 'energy_cost_usd_kwh': 0.089, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -0.8, 'ease_of_doing_business_rank': 122, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'C'}, 'export_products': [{'name': 'Textiles', 'share': 62.1, 'value_usd': 0.31, 'type': 'Manufacture'}, {'name': 'Diamants', 'share': 28.4, 'value_usd': 0.14, 'type': 'Minier'}], 'competitive_export_products': [{'name': 'Textiles AGOA', 'advantage': 'Accès USA + main d\'œuvre qualifiée', 'potential_usd': 0.8, 'type': 'Manufacture'}, {'name': 'Diamants qualité', 'advantage': 'Mine Letšeng + diamants exceptionnels', 'potential_usd': 0.4, 'type': 'Minier'}], 'infrastructure': {'routes_km': 5940, 'routes_pavees_pct': 17.0, 'voies_ferrees_km': 2.6, 'ports_principaux': 0, 'ports_details': ['Accès via Durban'], 'aeroports_internationaux': 1, 'aeroports_details': ['Maseru Moshoeshoe I']}, 'key_sectors': [{'name': 'Services', 'pib_share': 51.0, 'description': 'Commerce'}, {'name': 'Industrie', 'pib_share': 33.0, 'description': 'Textile et mines'}], 'top_trade_partners': ['Afrique du Sud', 'États-Unis', 'Belgique'], 'investment_opportunities': ['Textiles', 'Hydroélectricité'], 'main_exports': ['Textiles (62%)', 'Diamants (28%)'], 'main_imports': ['Produits alimentaires (25%)', 'Véhicules (20%)'], 'zlecaf_potential': {'level': 'Modéré', 'description': 'Niche manufacturière', 'key_opportunities': ['Textile régional', 'Énergie verte']}},

    "MUS": {'name': 'Maurice', 'gdp_usd_2024': 14.4, 'gdp_per_capita_2024': 11328, 'population_2024': 1270000, 'development_index': 0.802, 'hdi_africa_rank': 1, 'hdi_world_rank': 63, 'africa_rank': 30, 'growth_forecast_2024': '6.5%', 'external_debt_to_gdp_ratio': 89.4, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 6.1, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 10.8, 'foreign_reserves_months': 11.2, 'energy_cost_usd_kwh': 0.189, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -2.4, 'ease_of_doing_business_rank': 13, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'A3'}, 'export_products': [{'name': 'Textiles', 'share': 45.8, 'value_usd': 1.2, 'type': 'Manufacture'}, {'name': 'Sucre', 'share': 12.1, 'value_usd': 0.3, 'type': 'Agriculture'}], 'competitive_export_products': [{'name': 'Services financiers offshore', 'advantage': 'Régulation + hub Océan Indien', 'potential_usd': 2.1, 'type': 'Services'}, {'name': 'Tourisme haut de gamme', 'advantage': 'Île tropicale + luxe + sécurité', 'potential_usd': 2.8, 'type': 'Services'}], 'infrastructure': {'routes_km': 2428, 'routes_pavees_pct': 100.0, 'voies_ferrees_km': 0, 'ports_principaux': 1, 'ports_details': ['Port Louis'], 'aeroports_internationaux': 1, 'aeroports_details': ['Port Louis Sir Seewoosagur Ramgoolam']}, 'key_sectors': [{'name': 'Services', 'pib_share': 75.0, 'description': 'Finance et tourisme'}, {'name': 'Industrie', 'pib_share': 21.0, 'description': 'Textile'}], 'top_trade_partners': ['France', 'Royaume-Uni', 'Inde', 'Chine'], 'investment_opportunities': ['Fintech', 'Économie bleue', 'Hub régional'], 'main_exports': ['Textiles (46%)', 'Services financiers (15%)'], 'main_imports': ['Machines (20%)', 'Carburants (15%)'], 'zlecaf_potential': {'level': 'Très Élevé', 'description': 'Hub de services pour Afrique de l\'Est', 'key_opportunities': ['Hub financier régional', 'Services aux entreprises']}},

    "SDN": {'name': 'Soudan', 'gdp_usd_2024': 20.0, 'gdp_per_capita_2024': 441, 'population_2024': 45400000, 'development_index': 0.508, 'hdi_africa_rank': 39, 'hdi_world_rank': 172, 'africa_rank': 17, 'growth_forecast_2024': '-12.0%', 'external_debt_to_gdp_ratio': 256.7, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 78.9, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 138.4, 'foreign_reserves_months': 0.1, 'energy_cost_usd_kwh': 0.067, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -8.2, 'ease_of_doing_business_rank': 172, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'E'}, 'export_products': [{'name': 'Or', 'share': 68.2, 'value_usd': 2.1, 'type': 'Minier'}, {'name': 'Sésame', 'share': 8.1, 'value_usd': 0.25, 'type': 'Agriculture'}], 'competitive_export_products': [{'name': 'Gomme arabique', 'advantage': '1er producteur mondial + monopole', 'potential_usd': 0.8, 'type': 'Agriculture'}, {'name': 'Or artisanal', 'advantage': 'Réserves importantes + potentiel', 'potential_usd': 4.2, 'type': 'Minier'}], 'infrastructure': {'routes_km': 11900, 'routes_pavees_pct': 36.0, 'voies_ferrees_km': 4578, 'ports_principaux': 1, 'ports_details': ['Port-Soudan'], 'aeroports_internationaux': 1, 'aeroports_details': ['Khartoum']}, 'key_sectors': [{'name': 'Agriculture', 'pib_share': 43.0, 'description': 'Cultures et élevage'}, {'name': 'Services', 'pib_share': 37.0, 'description': 'Commerce'}], 'top_trade_partners': ['Chine', 'Émirats Arabes Unis', 'Arabie Saoudite'], 'investment_opportunities': ['Agriculture', 'Mines', 'Infrastructure'], 'main_exports': ['Or (68%)', 'Sésame (8%)'], 'main_imports': ['Machines (30%)', 'Produits alimentaires (25%)'], 'zlecaf_potential': {'level': 'Élevé', 'description': 'Énorme potentiel post-stabilisation', 'key_opportunities': ['Grenier de l\'Afrique', 'Ressources minières']}},

    "SOM": {'name': 'Somalie', 'gdp_usd_2024': 8.3, 'gdp_per_capita_2024': 499, 'population_2024': 16600000, 'development_index': 0.361, 'hdi_africa_rank': 54, 'hdi_world_rank': 189, 'africa_rank': 32, 'growth_forecast_2024': '2.4%', 'external_debt_to_gdp_ratio': 64.4, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 0.8, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 6.2, 'foreign_reserves_months': 2.1, 'energy_cost_usd_kwh': 0.298, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -3.8, 'ease_of_doing_business_rank': 190, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'E'}, 'export_products': [{'name': 'Bétail vivant', 'share': 65.2, 'value_usd': 0.4, 'type': 'Agriculture'}, {'name': 'Bananes', 'share': 12.1, 'value_usd': 0.07, 'type': 'Agriculture'}], 'competitive_export_products': [{'name': 'Bétail de qualité', 'advantage': 'Cheptel important + demande Golfe', 'potential_usd': 1.2, 'type': 'Agriculture'}, {'name': 'Pêche industrielle', 'advantage': 'Côte la plus longue d\'Afrique + ZEE riche', 'potential_usd': 2.1, 'type': 'Agriculture'}], 'infrastructure': {'routes_km': 22100, 'routes_pavees_pct': 11.8, 'voies_ferrees_km': 0, 'ports_principaux': 3, 'ports_details': ['Mogadiscio', 'Berbera'], 'aeroports_internationaux': 2, 'aeroports_details': ['Mogadiscio Aden Adde']}, 'key_sectors': [{'name': 'Agriculture', 'pib_share': 75.0, 'description': 'Élevage et pêche'}, {'name': 'Services', 'pib_share': 20.0, 'description': 'Commerce'}], 'top_trade_partners': ['Émirats Arabes Unis', 'Arabie Saoudite', 'Inde'], 'investment_opportunities': ['Pêche', 'Élevage', 'Télécommunications'], 'main_exports': ['Bétail vivant (65%)', 'Bananes (12%)'], 'main_imports': ['Produits alimentaires (30%)', 'Carburants (25%)'], 'zlecaf_potential': {'level': 'Élevé', 'description': 'Potentiel côtier post-stabilisation', 'key_opportunities': ['Économie bleue', 'Export bétail']}},

    "SSD": {'name': 'Soudan du Sud', 'gdp_usd_2024': 3.1, 'gdp_per_capita_2024': 275, 'population_2024': 11300000, 'development_index': 0.385, 'hdi_africa_rank': 52, 'hdi_world_rank': 191, 'africa_rank': 49, 'growth_forecast_2024': '7.9%', 'external_debt_to_gdp_ratio': 34.2, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 8.9, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 7.9, 'foreign_reserves_months': 1.1, 'energy_cost_usd_kwh': 0.398, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': 1.8, 'ease_of_doing_business_rank': 185, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'E'}, 'export_products': [{'name': 'Pétrole brut', 'share': 95.2, 'value_usd': 1.8, 'type': 'Énergie'}, {'name': 'Or', 'share': 2.1, 'value_usd': 0.04, 'type': 'Minier'}], 'competitive_export_products': [{'name': 'Pétrole léger', 'advantage': 'Réserves prouvées + qualité + pipeline', 'potential_usd': 4.2, 'type': 'Énergie'}, {'name': 'Agriculture irriguée', 'advantage': 'Terres fertiles + Nil + potentiel énorme', 'potential_usd': 2.1, 'type': 'Agriculture'}], 'infrastructure': {'routes_km': 7000, 'routes_pavees_pct': 4.0, 'voies_ferrees_km': 248, 'ports_principaux': 0, 'ports_details': ['Accès via Port-Soudan'], 'aeroports_internationaux': 1, 'aeroports_details': ['Juba']}, 'key_sectors': [{'name': 'Pétrole', 'pib_share': 60.0, 'description': 'Extraction'}, {'name': 'Agriculture', 'pib_share': 25.0, 'description': 'Élevage'}], 'top_trade_partners': ['Chine', 'Ouganda', 'Kenya'], 'investment_opportunities': ['Agriculture', 'Infrastructure', 'Pétrole'], 'main_exports': ['Pétrole brut (95%)', 'Or (2%)'], 'main_imports': ['Produits alimentaires (35%)', 'Machines (25%)'], 'zlecaf_potential': {'level': 'Très Élevé', 'description': 'Potentiel énorme post-stabilisation', 'key_opportunities': ['Grenier régional', 'Hub énergétique']}},

    "STP": {'name': 'São Tomé-et-Príncipe', 'gdp_usd_2024': 0.5, 'gdp_per_capita_2024': 2267, 'population_2024': 220000, 'development_index': 0.618, 'hdi_africa_rank': 20, 'hdi_world_rank': 138, 'africa_rank': 55, 'growth_forecast_2024': '1.8%', 'external_debt_to_gdp_ratio': 87.9, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 12.1, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 18.1, 'foreign_reserves_months': 3.8, 'energy_cost_usd_kwh': 0.298, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -0.08, 'ease_of_doing_business_rank': 170, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'D'}, 'export_products': [{'name': 'Cacao', 'share': 78.2, 'value_usd': 0.014, 'type': 'Agriculture'}, {'name': 'Café', 'share': 12.1, 'value_usd': 0.002, 'type': 'Agriculture'}], 'competitive_export_products': [{'name': 'Cacao bio premium', 'advantage': 'Origine unique + qualité + bio', 'potential_usd': 0.08, 'type': 'Agriculture'}, {'name': 'Tourisme écologique', 'advantage': 'Biodiversité unique + écotourisme', 'potential_usd': 0.2, 'type': 'Services'}], 'infrastructure': {'routes_km': 320, 'routes_pavees_pct': 68.0, 'voies_ferrees_km': 0, 'ports_principaux': 1, 'ports_details': ['São Tomé'], 'aeroports_internationaux': 1, 'aeroports_details': ['São Tomé']}, 'key_sectors': [{'name': 'Services', 'pib_share': 74.0, 'description': 'Tourisme'}, {'name': 'Agriculture', 'pib_share': 18.0, 'description': 'Cacao'}], 'top_trade_partners': ['Allemagne', 'Portugal', 'Belgique'], 'investment_opportunities': ['Écotourisme', 'Agriculture bio'], 'main_exports': ['Cacao (78%)', 'Café (12%)'], 'main_imports': ['Produits alimentaires (28%)', 'Carburants (22%)'], 'zlecaf_potential': {'level': 'Modéré', 'description': 'Niche écologique', 'key_opportunities': ['Cacao premium', 'Écotourisme']}},

    "SWZ": {'name': 'Eswatini', 'gdp_usd_2024': 4.7, 'gdp_per_capita_2024': 4019, 'population_2024': 1170000, 'development_index': 0.611, 'hdi_africa_rank': 21, 'hdi_world_rank': 144, 'africa_rank': 51, 'growth_forecast_2024': '2.7%', 'external_debt_to_gdp_ratio': 41.8, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 8.2, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 4.8, 'foreign_reserves_months': 3.1, 'energy_cost_usd_kwh': 0.089, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': 0.2, 'ease_of_doing_business_rank': 121, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'B'}, 'export_products': [{'name': 'Concentrés de sucre', 'share': 18.2, 'value_usd': 0.12, 'type': 'Agriculture'}, {'name': 'Textiles', 'share': 16.8, 'value_usd': 0.11, 'type': 'Manufacture'}], 'competitive_export_products': [{'name': 'Sucre premium', 'advantage': 'Qualité élevée + accords commerciaux', 'potential_usd': 0.3, 'type': 'Agriculture'}, {'name': 'Tourisme culturel', 'advantage': 'Culture swazi + nature + sécurité', 'potential_usd': 0.4, 'type': 'Services'}], 'infrastructure': {'routes_km': 3594, 'routes_pavees_pct': 30.0, 'voies_ferrees_km': 301, 'ports_principaux': 0, 'ports_details': ['Accès via Durban'], 'aeroports_internationaux': 1, 'aeroports_details': ['Matsapha King Mswati III']}, 'key_sectors': [{'name': 'Services', 'pib_share': 59.0, 'description': 'Commerce'}, {'name': 'Industrie', 'pib_share': 28.0, 'description': 'Manufacture'}], 'top_trade_partners': ['Afrique du Sud', 'États-Unis', 'Royaume-Uni'], 'investment_opportunities': ['Agroalimentaire', 'Textiles', 'Tourisme'], 'main_exports': ['Sucre (18%)', 'Textiles (17%)'], 'main_imports': ['Machines (22%)', 'Produits alimentaires (18%)'], 'zlecaf_potential': {'level': 'Modéré', 'description': 'Économie diversifiée avec niches', 'key_opportunities': ['Agroalimentaire régional', 'Hub manufacturier']}},

    "SYC": {'name': 'Seychelles', 'gdp_usd_2024': 1.9, 'gdp_per_capita_2024': 18795, 'population_2024': 100000, 'development_index': 0.796, 'hdi_africa_rank': 2, 'hdi_world_rank': 67, 'africa_rank': 56, 'growth_forecast_2024': '3.1%', 'external_debt_to_gdp_ratio': 67.8, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 4.2, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 1.8, 'foreign_reserves_months': 4.8, 'energy_cost_usd_kwh': 0.278, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -0.8, 'ease_of_doing_business_rank': 100, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'A4'}, 'export_products': [{'name': 'Poisson transformé', 'share': 94.2, 'value_usd': 0.48, 'type': 'Agriculture'}, {'name': 'Cannelle', 'share': 2.1, 'value_usd': 0.01, 'type': 'Agriculture'}], 'competitive_export_products': [{'name': 'Tourisme de luxe', 'advantage': 'Îles paradisiaques + exclusivité', 'potential_usd': 2.8, 'type': 'Services'}, {'name': 'Économie bleue', 'advantage': 'Océan + durabilité + innovation marine', 'potential_usd': 1.2, 'type': 'Services'}], 'infrastructure': {'routes_km': 526, 'routes_pavees_pct': 96.0, 'voies_ferrees_km': 0, 'ports_principaux': 1, 'ports_details': ['Victoria'], 'aeroports_internationaux': 1, 'aeroports_details': ['Victoria Seychelles']}, 'key_sectors': [{'name': 'Services', 'pib_share': 83.0, 'description': 'Tourisme et finance'}, {'name': 'Agriculture', 'pib_share': 4.0, 'description': 'Pêche'}], 'top_trade_partners': ['France', 'Royaume-Uni', 'Espagne'], 'investment_opportunities': ['Économie bleue', 'Tourisme durable'], 'main_exports': ['Poisson transformé (94%)', 'Tourisme (services)'], 'main_imports': ['Produits alimentaires (25%)', 'Machines (20%)'], 'zlecaf_potential': {'level': 'Élevé', 'description': 'Hub de services océan Indien', 'key_opportunities': ['Hub maritime régional', 'Économie bleue innovante']}},

    "TCD": {'name': 'Tchad', 'gdp_usd_2024': 11.8, 'gdp_per_capita_2024': 695, 'population_2024': 17000000, 'development_index': 0.394, 'hdi_africa_rank': 51, 'hdi_world_rank': 190, 'africa_rank': 26, 'growth_forecast_2024': '3.1%', 'external_debt_to_gdp_ratio': 48.9, 'external_debt_source': 'FMI - Debt Sustainability Analysis 2024', 'internal_debt_to_gdp_ratio': 8.1, 'internal_debt_source': 'Banque Mondiale - Public Debt Statistics 2024', 'inflation_rate_2024': 4.2, 'foreign_reserves_months': 2.8, 'energy_cost_usd_kwh': 0.398, 'energy_cost_source': 'Banque Mondiale - Energy Statistics 2024', 'trade_balance_usd': -0.8, 'ease_of_doing_business_rank': 181, 'risk_ratings': {'sp': 'Non noté', 'moodys': 'Non noté', 'fitch': 'Non noté', 'coface': 'E'}, 'export_products': [{'name': 'Pétrole brut', 'share': 88.2, 'value_usd': 2.8, 'type': 'Énergie'}, {'name': 'Coton', 'share': 4.8, 'value_usd': 0.15, 'type': 'Agriculture'}], 'competitive_export_products': [{'name': 'Bétail de qualité', 'advantage': 'Cheptel important + marchés régionaux', 'potential_usd': 1.2, 'type': 'Agriculture'}, {'name': 'Gomme arabique', 'advantage': 'Production + qualité + demande mondiale', 'potential_usd': 0.4, 'type': 'Agriculture'}], 'infrastructure': {'routes_km': 40000, 'routes_pavees_pct': 0.8, 'voies_ferrees_km': 0, 'ports_principaux': 0, 'ports_details': ['Accès via Douala'], 'aeroports_internationaux': 1, 'aeroports_details': ['N\'Djamena Hassan Djamous']}, 'key_sectors': [{'name': 'Agriculture', 'pib_share': 52.0, 'description': 'Élevage et cultures'}, {'name': 'Services', 'pib_share': 33.0, 'description': 'Commerce'}], 'top_trade_partners': ['États-Unis', 'Chine', 'France'], 'investment_opportunities': ['Agriculture', 'Élevage', 'Mines'], 'main_exports': ['Pétrole brut (88%)', 'Coton (5%)'], 'main_imports': ['Machines (25%)', 'Produits alimentaires (23%)'], 'zlecaf_potential': {'level': 'Élevé', 'description': 'Potentiel pastoral et minier', 'key_opportunities': ['Hub pastoral sahélien', 'Agriculture irriguée']}}
}

def add_missing_countries():
    """Ajouter les 16 pays restants à country_data.py"""
    
    # Lire le fichier actuel
    with open('/app/backend/country_data.py', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Ajouter les 5 premiers pays du fichier missing_21_countries.py
    exec(open('/app/backend/missing_21_countries.py').read())
    
    # Trouver la fin du dictionnaire REAL_COUNTRY_DATA
    insertion_point = content.rfind('}')
    
    # Préparer le texte à insérer
    countries_to_add = []
    
    # Ajouter les pays des deux sources
    for iso3, data in MISSING_COUNTRIES_DATA.items():
        countries_to_add.append(f'    "{iso3}": {data},')
    
    for iso3, data in REMAINING_COUNTRIES.items():
        countries_to_add.append(f'    "{iso3}": {data},')
    
    new_countries_text = '\n\n' + '\n\n'.join(countries_to_add) + '\n'
    
    # Insérer les nouveaux pays
    updated_content = content[:insertion_point] + new_countries_text + content[insertion_point:]
    
    # Écrire le fichier mis à jour
    with open('/app/backend/country_data.py', 'w', encoding='utf-8') as f:
        f.write(updated_content)
    
    print("✅ Tous les 21 pays manquants ont été ajoutés!")

if __name__ == "__main__":
    add_missing_countries()