# 21 derniers pays africains pour compléter les 54 pays ZLECAf

FINAL_21_COUNTRIES = {
    "BFA": {  # Burkina Faso
        "name": "Burkina Faso",
        "gdp_usd_2024": 20.1,
        "gdp_per_capita_2024": 912,
        "population_2024": 22000000,
        "development_index": 0.449,
        "hdi_africa_rank": 45,
        "hdi_world_rank": 184,
        "africa_rank": 39,
        "growth_forecast_2024": "5.8%",
        "external_debt_to_gdp_ratio": 61.9,
        "inflation_rate_2024": 2.1,
        "foreign_reserves_months": 3.8,
        "energy_cost_usd_kwh": 0.289,
        "trade_balance_usd": -1.2,
        "ease_of_doing_business_rank": 151,
        "risk_ratings": {"sp": "B-", "moodys": "B3", "fitch": "B-", "coface": "D"},
        "export_products": [{"name": "Or", "share": 67.8, "value_usd": 2.1, "type": "Minier"}, {"name": "Coton", "share": 19.4, "value_usd": 0.6, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Or", "advantage": "Production croissante + potentiel", "potential_usd": 3.8, "type": "Minier"}, {"name": "Coton bio", "advantage": "Certification + qualité", "potential_usd": 1.2, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 15304, "routes_pavees_pct": 16.0, "voies_ferrees_km": 622, "ports_principaux": 0, "ports_details": ["Accès via Abidjan", "Lomé"], "aeroports_internationaux": 1, "aeroports_details": ["Ouagadougou"]}
    },

    "BDI": {  # Burundi
        "name": "Burundi",
        "gdp_usd_2024": 3.8,
        "gdp_per_capita_2024": 308,
        "population_2024": 12400000,
        "development_index": 0.426,
        "hdi_africa_rank": 46,
        "hdi_world_rank": 187,
        "africa_rank": 51,
        "growth_forecast_2024": "2.9%",
        "external_debt_to_gdp_ratio": 69.4,
        "inflation_rate_2024": 26.3,
        "foreign_reserves_months": 1.2,
        "energy_cost_usd_kwh": 0.312,
        "trade_balance_usd": -0.8,
        "ease_of_doing_business_rank": 166,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "E"},
        "export_products": [{"name": "Café", "share": 54.2, "value_usd": 0.1, "type": "Agriculture"}, {"name": "Thé", "share": 21.3, "value_usd": 0.04, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Café premium", "advantage": "Altitude + terroir unique", "potential_usd": 0.4, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 12322, "routes_pavees_pct": 10.4, "voies_ferrees_km": 0, "ports_principaux": 0, "ports_details": ["Accès via Dar es Salaam"], "aeroports_internationaux": 1, "aeroports_details": ["Bujumbura Melchior Ndadaye"]}
    },

    "CMR": {  # Cameroun
        "name": "Cameroun",
        "gdp_usd_2024": 48.3,
        "gdp_per_capita_2024": 1780,
        "population_2024": 27100000,
        "development_index": 0.563,
        "hdi_africa_rank": 29,
        "hdi_world_rank": 151,
        "africa_rank": 20,
        "growth_forecast_2024": "4.2%",
        "external_debt_to_gdp_ratio": 43.8,
        "internal_debt_to_gdp_ratio": 18.2,
        "inflation_rate_2024": 4.1,
        "foreign_reserves_months": 3.9,
        "energy_cost_usd_kwh": 0.089,
        "trade_balance_usd": -0.8,
        "ease_of_doing_business_rank": 167,
        "risk_ratings": {"sp": "B", "moodys": "B2", "fitch": "B", "coface": "C"},
        "export_products": [{"name": "Pétrole brut", "share": 36.8, "value_usd": 1.9, "type": "Énergie"}, {"name": "Cacao", "share": 15.2, "value_usd": 0.8, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Cacao transformé", "advantage": "4ème producteur mondial + transformation", "potential_usd": 2.1, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 77589, "routes_pavees_pct": 8.6, "voies_ferrees_km": 987, "ports_principaux": 1, "ports_details": ["Douala"], "aeroports_internationaux": 3, "aeroports_details": ["Douala", "Yaoundé Nsimalen", "Garoua"]}
    },

    "CPV": {  # Cap-Vert
        "name": "Cap-Vert",
        "gdp_usd_2024": 2.3,
        "gdp_per_capita_2024": 4103,
        "population_2024": 560000,
        "development_index": 0.665,
        "hdi_africa_rank": 12,
        "hdi_world_rank": 127,
        "africa_rank": 53,
        "growth_forecast_2024": "4.8%",
        "external_debt_to_gdp_ratio": 136.2,
        "inflation_rate_2024": 3.1,
        "foreign_reserves_months": 5.8,
        "energy_cost_usd_kwh": 0.298,
        "trade_balance_usd": -0.7,
        "ease_of_doing_business_rank": 137,
        "risk_ratings": {"sp": "B", "moodys": "B1", "fitch": "B", "coface": "C"},
        "export_products": [{"name": "Produits de la pêche", "share": 45.2, "value_usd": 0.09, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Tourisme", "advantage": "Îles + climat + sécurité", "potential_usd": 1.2, "type": "Services"}],
        "infrastructure": {"routes_km": 1350, "routes_pavees_pct": 78.0, "voies_ferrees_km": 0, "ports_principaux": 2, "ports_details": ["Praia", "Mindelo"], "aeroports_internationaux": 4, "aeroports_details": ["Praia Nelson Mandela", "Sal Amílcar Cabral"]}
    },

    "CAF": {  # République Centrafricaine
        "name": "République Centrafricaine",
        "gdp_usd_2024": 2.8,
        "gdp_per_capita_2024": 581,
        "population_2024": 4800000,
        "development_index": 0.397,
        "hdi_africa_rank": 49,
        "hdi_world_rank": 188,
        "africa_rank": 52,
        "growth_forecast_2024": "1.2%",
        "external_debt_to_gdp_ratio": 52.8,
        "inflation_rate_2024": 4.2,
        "foreign_reserves_months": 2.1,
        "energy_cost_usd_kwh": 0.445,
        "trade_balance_usd": -0.2,
        "ease_of_doing_business_rank": 184,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "E"},
        "export_products": [{"name": "Diamants", "share": 48.5, "value_usd": 0.08, "type": "Minier"}],
        "competitive_export_products": [{"name": "Bois tropical", "advantage": "Forêts + essences rares", "potential_usd": 0.4, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 24307, "routes_pavees_pct": 2.6, "voies_ferrees_km": 0, "ports_principaux": 0, "ports_details": ["Accès via Douala", "Pointe-Noire"], "aeroports_internationaux": 1, "aeroports_details": ["Bangui M'Poko"]}
    },

    "TCD": {  # Tchad
        "name": "Tchad",
        "gdp_usd_2024": 15.9,
        "gdp_per_capita_2024": 952,
        "population_2024": 16700000,
        "development_index": 0.394,
        "hdi_africa_rank": 51,
        "hdi_world_rank": 190,
        "africa_rank": 40,
        "growth_forecast_2024": "3.8%",
        "external_debt_to_gdp_ratio": 52.1,
        "inflation_rate_2024": 4.6,
        "foreign_reserves_months": 1.8,
        "energy_cost_usd_kwh": 0.234,
        "trade_balance_usd": 1.2,
        "ease_of_doing_business_rank": 181,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "E"},
        "export_products": [{"name": "Pétrole brut", "share": 83.2, "value_usd": 2.8, "type": "Énergie"}],
        "competitive_export_products": [{"name": "Bétail", "advantage": "Cheptel important + marchés régionaux", "potential_usd": 1.1, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 44000, "routes_pavees_pct": 0.8, "voies_ferrees_km": 0, "ports_principaux": 0, "ports_details": ["Accès via Douala", "Port-Soudan"], "aeroports_internationaux": 1, "aeroports_details": ["N'Djamena Hassan Djamous"]}
    },

    "COM": {  # Comores
        "name": "Comores",
        "gdp_usd_2024": 1.4,
        "gdp_per_capita_2024": 1606,
        "population_2024": 870000,
        "development_index": 0.558,
        "hdi_africa_rank": 31,
        "hdi_world_rank": 156,
        "africa_rank": 54,
        "growth_forecast_2024": "3.2%",
        "external_debt_to_gdp_ratio": 32.4,
        "inflation_rate_2024": 1.8,
        "foreign_reserves_months": 7.2,
        "energy_cost_usd_kwh": 0.423,
        "trade_balance_usd": -0.2,
        "ease_of_doing_business_rank": 164,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "E"},
        "export_products": [{"name": "Vanille", "share": 36.8, "value_usd": 0.02, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Épices rares", "advantage": "Ylang-ylang + vanille + girofle", "potential_usd": 0.2, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 880, "routes_pavees_pct": 76.5, "voies_ferrees_km": 0, "ports_principaux": 3, "ports_details": ["Moroni", "Mutsamudu", "Fomboni"], "aeroports_internationaux": 3, "aeroports_details": ["Moroni Prince Said Ibrahim"]}
    },

    "COG": {  # République du Congo
        "name": "République du Congo",
        "gdp_usd_2024": 14.8,
        "gdp_per_capita_2024": 2650,
        "population_2024": 5600000,
        "development_index": 0.571,
        "hdi_africa_rank": 28,
        "hdi_world_rank": 149,
        "africa_rank": 41,
        "growth_forecast_2024": "1.8%",
        "external_debt_to_gdp_ratio": 107.6,
        "inflation_rate_2024": 2.1,
        "foreign_reserves_months": 2.8,
        "energy_cost_usd_kwh": 0.067,
        "trade_balance_usd": 3.2,
        "ease_of_doing_business_rank": 180,
        "risk_ratings": {"sp": "B-", "moodys": "B3", "fitch": "B-", "coface": "D"},
        "export_products": [{"name": "Pétrole brut", "share": 79.4, "value_usd": 6.8, "type": "Énergie"}],
        "competitive_export_products": [{"name": "Bois tropical", "advantage": "Forêts du bassin du Congo", "potential_usd": 1.8, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 24000, "routes_pavees_pct": 17.0, "voies_ferrees_km": 795, "ports_principaux": 1, "ports_details": ["Pointe-Noire"], "aeroports_internationaux": 2, "aeroports_details": ["Brazzaville Maya-Maya", "Pointe-Noire Agostinho Neto"]}
    },

    "DJI": {  # Djibouti
        "name": "Djibouti",
        "gdp_usd_2024": 4.1,
        "gdp_per_capita_2024": 4143,
        "population_2024": 990000,
        "development_index": 0.524,
        "hdi_africa_rank": 37,
        "hdi_world_rank": 171,
        "africa_rank": 50,
        "growth_forecast_2024": "5.1%",
        "external_debt_to_gdp_ratio": 77.8,
        "inflation_rate_2024": 1.9,
        "foreign_reserves_months": 4.8,
        "energy_cost_usd_kwh": 0.298,
        "trade_balance_usd": -1.2,
        "ease_of_doing_business_rank": 112,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "C"},
        "export_products": [{"name": "Services de transit", "share": 68.2, "value_usd": 0.8, "type": "Services"}],
        "competitive_export_products": [{"name": "Services logistiques", "advantage": "Position géostratégique + port", "potential_usd": 2.1, "type": "Services"}],
        "infrastructure": {"routes_km": 2893, "routes_pavees_pct": 12.6, "voies_ferrees_km": 97, "ports_principaux": 1, "ports_details": ["Djibouti"], "aeroports_internationaux": 1, "aeroports_details": ["Djibouti Ambouli"]}
    },

    "GNQ": {  # Guinée Équatoriale
        "name": "Guinée Équatoriale",
        "gdp_usd_2024": 12.1,
        "gdp_per_capita_2024": 8456,
        "population_2024": 1430000,
        "development_index": 0.596,
        "hdi_africa_rank": 24,
        "hdi_world_rank": 145,
        "africa_rank": 43,
        "growth_forecast_2024": "-2.1%",
        "external_debt_to_gdp_ratio": 43.2,
        "inflation_rate_2024": 4.8,
        "foreign_reserves_months": 8.2,
        "energy_cost_usd_kwh": 0.034,
        "trade_balance_usd": 2.1,
        "ease_of_doing_business_rank": 178,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "D"},
        "export_products": [{"name": "Pétrole brut", "share": 81.2, "value_usd": 4.8, "type": "Énergie"}],
        "competitive_export_products": [{"name": "Gaz naturel liquéfié", "advantage": "Réserves offshore + infrastructure", "potential_usd": 2.8, "type": "Énergie"}],
        "infrastructure": {"routes_km": 2880, "routes_pavees_pct": 0.0, "voies_ferrees_km": 0, "ports_principaux": 2, "ports_details": ["Malabo", "Bata"], "aeroports_internationaux": 1, "aeroports_details": ["Malabo"]}
    },

    "ERI": {  # Érythrée
        "name": "Érythrée",
        "gdp_usd_2024": 2.6,
        "gdp_per_capita_2024": 643,
        "population_2024": 4050000,
        "development_index": 0.459,
        "hdi_africa_rank": 44,
        "hdi_world_rank": 180,
        "africa_rank": 49,
        "growth_forecast_2024": "2.8%",
        "external_debt_to_gdp_ratio": 176.3,
        "inflation_rate_2024": 8.2,
        "foreign_reserves_months": 1.1,
        "energy_cost_usd_kwh": 0.187,
        "trade_balance_usd": -0.4,
        "ease_of_doing_business_rank": 189,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "E"},
        "export_products": [{"name": "Or", "share": 67.2, "value_usd": 0.4, "type": "Minier"}],
        "competitive_export_products": [{"name": "Mines d'or", "advantage": "Potentiel géologique + développement", "potential_usd": 1.2, "type": "Minier"}],
        "infrastructure": {"routes_km": 16000, "routes_pavees_pct": 21.8, "voies_ferrees_km": 306, "ports_principaux": 2, "ports_details": ["Massawa", "Assab"], "aeroports_internationaux": 1, "aeroports_details": ["Asmara"]}
    },

    "SWZ": {  # Eswatini
        "name": "Eswatini",
        "gdp_usd_2024": 4.6,
        "gdp_per_capita_2024": 3918,
        "population_2024": 1180000,
        "development_index": 0.608,
        "hdi_africa_rank": 22,
        "hdi_world_rank": 144,
        "africa_rank": 48,
        "growth_forecast_2024": "2.1%",
        "external_debt_to_gdp_ratio": 42.8,
        "inflation_rate_2024": 4.6,
        "foreign_reserves_months": 3.2,
        "energy_cost_usd_kwh": 0.098,
        "trade_balance_usd": 0.1,
        "ease_of_doing_business_rank": 121,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "C"},
        "export_products": [{"name": "Sucre", "share": 32.1, "value_usd": 0.6, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Sucre biologique", "advantage": "Production bio + marché premium", "potential_usd": 0.8, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 3594, "routes_pavees_pct": 30.0, "voies_ferrees_km": 301, "ports_principaux": 0, "ports_details": ["Accès via Durban", "Maputo"], "aeroports_internationaux": 1, "aeroports_details": ["Matsapha"]}
    },

    "GAB": {  # Gabon
        "name": "Gabon",
        "gdp_usd_2024": 20.8,
        "gdp_per_capita_2024": 8823,
        "population_2024": 2400000,
        "development_index": 0.706,
        "hdi_africa_rank": 8,
        "hdi_world_rank": 112,
        "africa_rank": 32,
        "growth_forecast_2024": "2.9%",
        "external_debt_to_gdp_ratio": 62.7,
        "internal_debt_to_gdp_ratio": 15.8,
        "inflation_rate_2024": 4.2,
        "foreign_reserves_months": 2.8,
        "energy_cost_usd_kwh": 0.078,
        "trade_balance_usd": 2.1,
        "ease_of_doing_business_rank": 169,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "C"},
        "export_products": [{"name": "Pétrole brut", "share": 80.2, "value_usd": 7.8, "type": "Énergie"}, {"name": "Manganèse", "share": 6.8, "value_usd": 0.7, "type": "Minier"}],
        "competitive_export_products": [{"name": "Bois précieux", "advantage": "Essences rares + gestion durable", "potential_usd": 1.8, "type": "Agriculture"}, {"name": "Manganèse", "advantage": "2ème producteur mondial", "potential_usd": 1.2, "type": "Minier"}],
        "infrastructure": {"routes_km": 10000, "routes_pavees_pct": 10.2, "voies_ferrees_km": 649, "ports_principaux": 1, "ports_details": ["Port-Gentil", "Libreville", "Owendo"], "aeroports_internationaux": 1, "aeroports_details": ["Libreville Léon M'Ba"]}
    },

    "LSO": {  # Lesotho
        "name": "Lesotho",
        "gdp_usd_2024": 2.2,
        "gdp_per_capita_2024": 1023,
        "population_2024": 2200000,
        "development_index": 0.514,
        "hdi_africa_rank": 38,
        "hdi_world_rank": 168,
        "africa_rank": 55,
        "growth_forecast_2024": "2.5%",
        "external_debt_to_gdp_ratio": 103.2,
        "inflation_rate_2024": 6.3,
        "foreign_reserves_months": 3.8,
        "energy_cost_usd_kwh": 0.143,
        "trade_balance_usd": -0.4,
        "ease_of_doing_business_rank": 122,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "C"},
        "export_products": [{"name": "Textiles", "share": 35.8, "value_usd": 0.3, "type": "Manufacture"}, {"name": "Diamants", "share": 28.1, "value_usd": 0.2, "type": "Minier"}],
        "competitive_export_products": [{"name": "Eau potable", "advantage": "Château d'eau régional + qualité", "potential_usd": 0.8, "type": "Services"}, {"name": "Textiles AGOA", "advantage": "Accès préférentiel USA", "potential_usd": 0.6, "type": "Manufacture"}],
        "infrastructure": {"routes_km": 5940, "routes_pavees_pct": 16.0, "voies_ferrees_km": 2, "ports_principaux": 0, "ports_details": ["Accès via Durban"], "aeroports_internationaux": 1, "aeroports_details": ["Maseru Moshoeshoe I"]}
    },

    "LBY": {  # Libye
        "name": "Libye",
        "gdp_usd_2024": 45.8,
        "gdp_per_capita_2024": 6716,
        "population_2024": 6800000,
        "development_index": 0.718,
        "hdi_africa_rank": 6,
        "hdi_world_rank": 104,
        "africa_rank": 22,
        "growth_forecast_2024": "7.4%",
        "external_debt_to_gdp_ratio": 155.8,
        "inflation_rate_2024": 2.1,
        "foreign_reserves_months": 18.2,
        "energy_cost_usd_kwh": 0.021,
        "trade_balance_usd": 8.9,
        "ease_of_doing_business_rank": 186,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "E"},
        "export_products": [{"name": "Pétrole brut", "share": 96.8, "value_usd": 18.2, "type": "Énergie"}],
        "competitive_export_products": [{"name": "Pétrole léger", "advantage": "Qualité premium + réserves", "potential_usd": 28.4, "type": "Énergie"}],
        "infrastructure": {"routes_km": 34000, "routes_pavees_pct": 57.0, "voies_ferrees_km": 0, "ports_principaux": 5, "ports_details": ["Tripoli", "Benghazi", "Misrata", "Tobruk"], "aeroports_internationaux": 3, "aeroports_details": ["Tripoli", "Benghazi Benina", "Misrata"]}
    },

    "MUS": {  # Maurice
        "name": "Maurice",
        "gdp_usd_2024": 15.2,
        "gdp_per_capita_2024": 11,
        "population_2024": 1300000,
        "development_index": 0.802,
        "hdi_africa_rank": 1,
        "hdi_world_rank": 63,
        "africa_rank": 56,  # Non ZLECAf mais inclus pour comparaison
        "growth_forecast_2024": "6.5%",
        "external_debt_to_gdp_ratio": 89.8,
        "internal_debt_to_gdp_ratio": 6.2,
        "inflation_rate_2024": 10.8,
        "foreign_reserves_months": 11.2,
        "energy_cost_usd_kwh": 0.198,
        "trade_balance_usd": -2.8,
        "ease_of_doing_business_rank": 13,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "A3"},
        "export_products": [{"name": "Textiles", "share": 46.2, "value_usd": 1.8, "type": "Manufacture"}, {"name": "Sucre", "share": 18.4, "value_usd": 0.7, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Services financiers offshore", "advantage": "Hub financier + stabilité", "potential_usd": 3.2, "type": "Services"}, {"name": "Tourisme haut de gamme", "advantage": "Destination premium + service", "potential_usd": 2.1, "type": "Services"}],
        "infrastructure": {"routes_km": 2428, "routes_pavees_pct": 98.0, "voies_ferrees_km": 0, "ports_principaux": 1, "ports_details": ["Port Louis"], "aeroports_internationaux": 1, "aeroports_details": ["Maurice Sir Seewoosagur Ramgoolam"]}
    },

    "STP": {  # Sao Tomé-et-Principe
        "name": "Sao Tomé-et-Principe",
        "gdp_usd_2024": 0.5,
        "gdp_per_capita_2024": 2267,
        "population_2024": 220000,
        "development_index": 0.618,
        "hdi_africa_rank": 20,
        "hdi_world_rank": 138,
        "africa_rank": 57,  # Plus petit pays africain
        "growth_forecast_2024": "2.8%",
        "external_debt_to_gdp_ratio": 96.8,
        "inflation_rate_2024": 18.1,
        "foreign_reserves_months": 4.8,
        "energy_cost_usd_kwh": 0.412,
        "trade_balance_usd": -0.1,
        "ease_of_doing_business_rank": 170,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "D"},
        "export_products": [{"name": "Cacao", "share": 78.2, "value_usd": 0.012, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Cacao bio premium", "advantage": "Qualité + certification bio", "potential_usd": 0.08, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 320, "routes_pavees_pct": 68.0, "voies_ferrees_km": 0, "ports_principaux": 1, "ports_details": ["São Tomé"], "aeroports_internationaux": 1, "aeroports_details": ["São Tomé"]}
    },

    "SYC": {  # Seychelles
        "name": "Seychelles",
        "gdp_usd_2024": 1.7,
        "gdp_per_capita_2024": 17152,
        "population_2024": 100000,
        "development_index": 0.785,
        "hdi_africa_rank": 2,
        "hdi_world_rank": 72,
        "africa_rank": 58,  # PIB/habitant le plus élevé d'Afrique
        "growth_forecast_2024": "3.8%",
        "external_debt_to_gdp_ratio": 68.8,
        "inflation_rate_2024": 2.8,
        "foreign_reserves_months": 4.2,
        "energy_cost_usd_kwh": 0.389,
        "trade_balance_usd": -0.8,
        "ease_of_doing_business_rank": 100,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "B"},
        "export_products": [{"name": "Poisson", "share": 92.8, "value_usd": 0.5, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Tourisme de luxe", "advantage": "Destination paradisiaque unique", "potential_usd": 1.8, "type": "Services"}],
        "infrastructure": {"routes_km": 526, "routes_pavees_pct": 96.0, "voies_ferrees_km": 0, "ports_principaux": 1, "ports_details": ["Victoria"], "aeroports_internationaux": 1, "aeroports_details": ["Mahé"]}
    },

    "SOM": {  # Somalie
        "name": "Somalie",
        "gdp_usd_2024": 12.3,
        "gdp_per_capita_2024": 775,
        "population_2024": 15900000,
        "development_index": 0.361,
        "hdi_africa_rank": 54,
        "hdi_world_rank": 191,
        "africa_rank": 44,
        "growth_forecast_2024": "2.4%",
        "external_debt_to_gdp_ratio": 64.2,
        "inflation_rate_2024": 6.8,
        "foreign_reserves_months": 2.1,
        "energy_cost_usd_kwh": 0.456,
        "trade_balance_usd": -2.8,
        "ease_of_doing_business_rank": 190,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "E"},
        "export_products": [{"name": "Bétail", "share": 65.8, "value_usd": 0.4, "type": "Agriculture"}, {"name": "Bananes", "share": 15.2, "value_usd": 0.09, "type": "Agriculture"}],
        "competitive_export_products": [{"name": "Élevage", "advantage": "Cheptel important + marchés régionaux", "potential_usd": 1.2, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 22100, "routes_pavees_pct": 11.8, "voies_ferrees_km": 0, "ports_principaux": 3, "ports_details": ["Mogadiscio", "Berbera", "Kismayo"], "aeroports_internationaux": 2, "aeroports_details": ["Mogadiscio Aden Adde", "Hargeisa"]}
    },

    "SSD": {  # Soudan du Sud
        "name": "Soudan du Sud",
        "gdp_usd_2024": 5.8,
        "gdp_per_capita_2024": 516,
        "population_2024": 11200000,
        "development_index": 0.385,
        "hdi_africa_rank": 52,
        "hdi_world_rank": 192,
        "africa_rank": 46,
        "growth_forecast_2024": "-0.2%",
        "external_debt_to_gdp_ratio": 34.8,
        "inflation_rate_2024": 78.5,
        "foreign_reserves_months": 0.8,
        "energy_cost_usd_kwh": 0.278,
        "trade_balance_usd": 1.2,
        "ease_of_doing_business_rank": 185,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "E"},
        "export_products": [{"name": "Pétrole brut", "share": 98.8, "value_usd": 1.2, "type": "Énergie"}],
        "competitive_export_products": [{"name": "Pétrole", "advantage": "Réserves importantes + potentiel", "potential_usd": 4.8, "type": "Énergie"}],
        "infrastructure": {"routes_km": 7000, "routes_pavees_pct": 4.0, "voies_ferrees_km": 0, "ports_principaux": 0, "ports_details": ["Accès via Port-Soudan"], "aeroports_internationaux": 1, "aeroports_details": ["Juba"]}
    },

    "SDN": {  # Soudan
        "name": "Soudan",
        "gdp_usd_2024": 24.9,
        "gdp_per_capita_2024": 546,
        "population_2024": 45600000,
        "development_index": 0.508,
        "hdi_africa_rank": 39,
        "hdi_world_rank": 172,
        "africa_rank": 23,
        "growth_forecast_2024": "-18.3%",
        "external_debt_to_gdp_ratio": 256.8,
        "inflation_rate_2024": 138.8,
        "foreign_reserves_months": 0.2,
        "energy_cost_usd_kwh": 0.034,
        "trade_balance_usd": -4.8,
        "ease_of_doing_business_rank": 171,
        "risk_ratings": {"sp": "Non noté", "moodys": "Non noté", "fitch": "Non noté", "coface": "E"},
        "export_products": [{"name": "Or", "share": 68.2, "value_usd": 1.2, "type": "Minier"}, {"name": "Pétrole brut", "share": 15.8, "value_usd": 0.3, "type": "Énergie"}],
        "competitive_export_products": [{"name": "Agriculture", "advantage": "Terres fertiles + Nil", "potential_usd": 8.2, "type": "Agriculture"}],
        "infrastructure": {"routes_km": 11900, "routes_pavees_pct": 36.3, "voies_ferrees_km": 4578, "ports_principaux": 1, "ports_details": ["Port-Soudan"], "aeroports_internationaux": 1, "aeroports_details": ["Khartoum"]}
    }
}