name: lyra-plus-ops

on:
  schedule:
    - cron: "15 6 * * 1"   # Tous les lundis à 06:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write    # nécessaire pour push
  actions: read
  checks: read

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (optionnel)
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl || true

      - name: Generate datasets (Lyra+ pipeline)
        run: |
          # TODO: remplacez --demo par l'intégration réelle (e‑Tariff/UNCTAD/OEC)
          # Option 1: Using shell script (recommended for better error handling)
          # ./afcfta_2025_datasets.sh --demo
          # Option 2: Using Python script directly
          python backend/make_release.py --demo

      - name: Commit & push data changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "lyra-plus-bot"
          git config user.email "lyra-plus-bot@users.noreply.github.com"
          git add frontend/public/data || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(ops): refresh AfCFTA datasets via Lyra+ weekly cron"
            git push
          else
            echo "No data changes to commit."
          fi
