name: lyra-plus-ops

on:
  schedule:
    - cron: "15 6 * * 1"   # Tous les lundis à 06:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write    # nécessaire pour push
  pull-requests: write    # nécessaire pour créer des PRs
  actions: read
  checks: read

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (optionnel)
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl || true

      - name: Generate datasets (Lyra+ pipeline)
        run: |
          # TODO: remplacez --demo par l'intégration réelle (e‑Tariff/UNCTAD/OEC)
          python backend/make_release.py --demo

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            frontend/public/data/**
          branch: lyra-plus-ops/refresh-data-${{ github.run_number }}
          commit-message: "chore(ops): refresh AfCFTA datasets via Lyra+ weekly cron"
          title: "🔄 Refresh AfCFTA datasets - Lyra+ weekly update"
          body: |
            ## Automated Data Refresh
            
            This PR contains the weekly refresh of AfCFTA datasets generated by the Lyra+ pipeline.
            
            ### Generated Files
            - `zlecaf_tariff_lines_by_country.json` - Tariff lines by country
            - `zlecaf_rules_of_origin.json` - Rules of origin by sector
            - `zlecaf_dismantling_schedule.csv` - Phase-out schedule
            - `zlecaf_tariff_origin_phase.json` - Integrated data
            - `zlecaf_africa_vs_world_tariffs.csv` - Tariff comparison
            
            ### Details
            - **Workflow Run**: #${{ github.run_number }}
            - **Triggered by**: ${{ github.event_name }}
            - **Generated at**: ${{ github.event.head_commit.timestamp || github.run_id }}
            
            **Note**: Currently running in demo mode with sample data. See `backend/make_release.py` for production integration.
          labels: |
            data
            afcfta
            lyra-plus
            automated
          delete-branch: true
